# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/excel_islemler/arkaplanayarla.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(962, 553)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.arkaplan = QtWidgets.QLabel(self.centralwidget)
        self.arkaplan.setGeometry(QtCore.QRect(0, -20, 960, 591))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.arkaplan.setFont(font)
        self.arkaplan.setText("")
        self.arkaplan.setObjectName("arkaplan")
        self.ulke1 = QtWidgets.QComboBox(self.centralwidget)
        self.ulke1.setGeometry(QtCore.QRect(90, 220, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ulke1.setFont(font)
        self.ulke1.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"background-color: rgb(0, 104, 132);")
        self.ulke1.setObjectName("ulke1")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke2 = QtWidgets.QComboBox(self.centralwidget)
        self.ulke2.setGeometry(QtCore.QRect(90, 310, 201, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.ulke2.setFont(font)
        self.ulke2.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 104, 132);")
        self.ulke2.setObjectName("ulke2")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.deger = QtWidgets.QTextEdit(self.centralwidget)
        self.deger.setGeometry(QtCore.QRect(90, 410, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.deger.setFont(font)
        self.deger.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 104, 132);")
        self.deger.setObjectName("deger")
        self.SKU = QtWidgets.QTextEdit(self.centralwidget)
        self.SKU.setGeometry(QtCore.QRect(630, 230, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SKU.setFont(font)
        self.SKU.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 104, 132);")
        self.SKU.setObjectName("SKU")
        self.Baslat = QtWidgets.QPushButton(self.centralwidget)
        self.Baslat.setGeometry(QtCore.QRect(410, 410, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Baslat.setFont(font)
        self.Baslat.setStyleSheet("background-color: rgb(252, 210, 79);\n"
"color: rgb(0, 0, 0);")
        self.Baslat.setObjectName("Baslat")
        self.dosyasec = QtWidgets.QPushButton(self.centralwidget)
        self.dosyasec.setGeometry(QtCore.QRect(650, 320, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dosyasec.setFont(font)
        self.dosyasec.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 104, 132);")
        self.dosyasec.setObjectName("dosyasec")
        self.dosya_adi = QtWidgets.QLabel(self.centralwidget)
        self.dosya_adi.setGeometry(QtCore.QRect(570, 410, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dosya_adi.setFont(font)
        self.dosya_adi.setText("")
        self.dosya_adi.setObjectName("dosya_adi")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ulke1.setItemText(0, _translate("MainWindow", "USA"))
        self.ulke1.setItemText(1, _translate("MainWindow", "Canada"))
        self.ulke1.setItemText(2, _translate("MainWindow", "Meksika"))
        self.ulke1.setItemText(3, _translate("MainWindow", "Birleşik Arap emirlikleri"))
        self.ulke1.setItemText(4, _translate("MainWindow", "Singapur"))
        self.ulke1.setItemText(5, _translate("MainWindow", "Avustralya"))
        self.ulke1.setItemText(6, _translate("MainWindow", "Japonya"))
        self.ulke1.setItemText(7, _translate("MainWindow", "Almanya"))
        self.ulke1.setItemText(8, _translate("MainWindow", "Brezilya"))
        self.ulke1.setItemText(9, _translate("MainWindow", "Fransa"))
        self.ulke1.setItemText(10, _translate("MainWindow", "Hollanda"))
        self.ulke2.setItemText(0, _translate("MainWindow", "USA"))
        self.ulke2.setItemText(1, _translate("MainWindow", "Canada"))
        self.ulke2.setItemText(2, _translate("MainWindow", "Meksika"))
        self.ulke2.setItemText(3, _translate("MainWindow", "Birleşik Arap emirlikleri"))
        self.ulke2.setItemText(4, _translate("MainWindow", "Singapur"))
        self.ulke2.setItemText(5, _translate("MainWindow", "Avustralya"))
        self.ulke2.setItemText(6, _translate("MainWindow", "Japonya"))
        self.ulke2.setItemText(7, _translate("MainWindow", "Almanya"))
        self.ulke2.setItemText(8, _translate("MainWindow", "Brezilya"))
        self.ulke2.setItemText(9, _translate("MainWindow", "Fransa"))
        self.ulke2.setItemText(10, _translate("MainWindow", "Hollanda"))
        self.Baslat.setText(_translate("MainWindow", "BAŞLAT"))
        self.dosyasec.setText(_translate("MainWindow", "Dsya seç"))

