# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:/masaüstü/yazılımileilgilihersey/onluk/excel islemler/ornek_goruntu.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 609)
        MainWindow.setStyleSheet("color: rgb(5, 61, 87);\n"
"background-color: rgb(248, 251, 253);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dosyasec = QtWidgets.QPushButton(self.centralwidget)
        self.dosyasec.setGeometry(QtCore.QRect(680, 110, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.dosyasec.setFont(font)
        self.dosyasec.setStyleSheet("background-color: rgb(160, 168, 178);")
        self.dosyasec.setObjectName("dosyasec")
        self.kupon_id_label_5 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_5.setGeometry(QtCore.QRect(290, 10, 301, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.kupon_id_label_5.setFont(font)
        self.kupon_id_label_5.setObjectName("kupon_id_label_5")
        self.dosya_adi = QtWidgets.QLabel(self.centralwidget)
        self.dosya_adi.setGeometry(QtCore.QRect(30, 110, 621, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.dosya_adi.setFont(font)
        self.dosya_adi.setObjectName("dosya_adi")
        self.deger = QtWidgets.QTextEdit(self.centralwidget)
        self.deger.setGeometry(QtCore.QRect(240, 180, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.deger.setFont(font)
        self.deger.setStyleSheet("background-color: rgb(160, 168, 178);")
        self.deger.setObjectName("deger")
        self.kupon_id_label_7 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_7.setGeometry(QtCore.QRect(30, 180, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.kupon_id_label_7.setFont(font)
        self.kupon_id_label_7.setObjectName("kupon_id_label_7")
        self.Baslat = QtWidgets.QPushButton(self.centralwidget)
        self.Baslat.setGeometry(QtCore.QRect(340, 280, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Baslat.setFont(font)
        self.Baslat.setStyleSheet("background-color: rgb(160, 168, 178);")
        self.Baslat.setObjectName("Baslat")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(490, 380, 321, 191))
        self.logo.setObjectName("logo")
        self.ulke1 = QtWidgets.QComboBox(self.centralwidget)
        self.ulke1.setGeometry(QtCore.QRect(30, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ulke1.setFont(font)
        self.ulke1.setObjectName("ulke1")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.ulke1.addItem("")
        self.kupon_id_label_8 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_8.setGeometry(QtCore.QRect(30, 360, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.kupon_id_label_8.setFont(font)
        self.kupon_id_label_8.setObjectName("kupon_id_label_8")
        self.kupon_id_label_9 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_9.setGeometry(QtCore.QRect(250, 360, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.kupon_id_label_9.setFont(font)
        self.kupon_id_label_9.setObjectName("kupon_id_label_9")
        self.ulke2 = QtWidgets.QComboBox(self.centralwidget)
        self.ulke2.setGeometry(QtCore.QRect(240, 430, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.ulke2.setFont(font)
        self.ulke2.setObjectName("ulke2")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.ulke2.addItem("")
        self.SKU = QtWidgets.QTextEdit(self.centralwidget)
        self.SKU.setGeometry(QtCore.QRect(590, 180, 181, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.SKU.setFont(font)
        self.SKU.setStyleSheet("background-color: rgb(160, 168, 178);")
        self.SKU.setObjectName("SKU")
        self.kupon_id_label_10 = QtWidgets.QLabel(self.centralwidget)
        self.kupon_id_label_10.setGeometry(QtCore.QRect(500, 180, 81, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.kupon_id_label_10.setFont(font)
        self.kupon_id_label_10.setObjectName("kupon_id_label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.dosyasec.setText(_translate("MainWindow", "Dsya seç"))
        self.kupon_id_label_5.setText(_translate("MainWindow", "Stoksuz Hesaplayıcı"))
        self.dosya_adi.setText(_translate("MainWindow", "Dosya Adı"))
        self.kupon_id_label_7.setText(_translate("MainWindow", "Karlılık Oranı: "))
        self.Baslat.setText(_translate("MainWindow", "BAŞLAT"))
        self.logo.setText(_translate("MainWindow", "Logo"))
        self.ulke1.setItemText(0, _translate("MainWindow", "USA"))
        self.ulke1.setItemText(1, _translate("MainWindow", "Canada"))
        self.ulke1.setItemText(2, _translate("MainWindow", "Meksika"))
        self.ulke1.setItemText(3, _translate("MainWindow", "Birleşik Arap emirlikleri"))
        self.ulke1.setItemText(4, _translate("MainWindow", "Singapur"))
        self.ulke1.setItemText(5, _translate("MainWindow", "Avustralya"))
        self.ulke1.setItemText(6, _translate("MainWindow", "Japonya"))
        self.ulke1.setItemText(7, _translate("MainWindow", "Almanya"))
        self.ulke1.setItemText(8, _translate("MainWindow", "Brezilya"))
        self.ulke1.setItemText(9, _translate("MainWindow", "Fransa"))
        self.ulke1.setItemText(10, _translate("MainWindow", "Hollanda"))
        self.kupon_id_label_8.setText(_translate("MainWindow", "1. ülke"))
        self.kupon_id_label_9.setText(_translate("MainWindow", "2. ülke"))
        self.ulke2.setItemText(0, _translate("MainWindow", "USA"))
        self.ulke2.setItemText(1, _translate("MainWindow", "Canada"))
        self.ulke2.setItemText(2, _translate("MainWindow", "Meksika"))
        self.ulke2.setItemText(3, _translate("MainWindow", "Birleşik Arap emirlikleri"))
        self.ulke2.setItemText(4, _translate("MainWindow", "Singapur"))
        self.ulke2.setItemText(5, _translate("MainWindow", "Avustralya"))
        self.ulke2.setItemText(6, _translate("MainWindow", "Japonya"))
        self.ulke2.setItemText(7, _translate("MainWindow", "Almanya"))
        self.ulke2.setItemText(8, _translate("MainWindow", "Brezilya"))
        self.ulke2.setItemText(9, _translate("MainWindow", "Fransa"))
        self.ulke2.setItemText(10, _translate("MainWindow", "Hollanda"))
        self.kupon_id_label_10.setText(_translate("MainWindow", "SKU: "))

